### ISSUE TITLE
Статистика выполненных задач работает неверно

### ISSUE THREAD

**Issue by orfosit** [leandr92/Academy_Devins#4]
При обновлении главной страницы "рандомно" меняется количество решённых задач.
![image](https://user-images.githubusercontent.com/61069195/207312835-2978a0d2-cdaf-4bd6-b491-3c7a6d5b0623.png)

Что-то не так со статистикой. Все задачи решены, но на главной странице в стастике это не отображается.

**Comment by leandr92** [comment]
Нормальная работа статистики восстановлена. Исправлен механизм кеширования.
