### ISSUE TITLE
Не работает drag-n-drop

### ISSUE THREAD

**Issue by orfosit** [leandr92/Academy_Devins#5]
Сообщение об ошибке от Евгений Букреев (29.11.2022 06:34:38)
В самом первом задании drag-n-drop'ом перетащил текст запроса из текста задания. Сервис текста запроса после этого не видит, хотя визуально он отображается, и не даёт текст редактировать

**Comment by leandr92** [comment]
Уже зафиксировано в issue #9. Закрыт из-за дублирования
