### ISSUE TITLE
Скрытая кнопка в задаче 22. Неверный счетчик задач.

### ISSUE THREAD

**Issue by orfosit** [leandr92/Academy_Devins#7]
При первом прохождении в задаче 22 отображается, словно есть ещё одна нерешенная задача, но перейти в неё нельзя)
Всего задач 22, отображает как 23
![image](https://user-images.githubusercontent.com/61069195/207341583-107a5f6c-c52d-4c1b-8f3e-5b841cb64847.png)

**Comment by leandr92** [comment]
Пользователь не учел, что ещё есть задача "Вводный инструктаж"
